import { defineField, defineType } from 'sanity'
import { Flame } from 'lucide-react'

export const urgencyPopup = defineType({
  name: 'urgencyPopup',
  title: 'Popup Urgencia de Agotamiento',
  type: 'document',
  icon: Flame,
  groups: [
    { name: 'general', title: 'General', default: true },
    { name: 'manual', title: 'Modo Manual' },
    { name: 'auto', title: 'Modo Automático' },
    { name: 'appearance', title: 'Diseño y Apariencia' },
  ],
  fields: [
    // --- GRUPO GENERAL ---
    defineField({
      name: 'isActive',
      title: '¿Activar Popup de Urgencia?',
      type: 'boolean',
      group: 'general',
      description: 'Activa o desactiva la aparición del popup de agotamiento en la tienda.',
      initialValue: true,
    }),
    defineField({
      name: 'mode',
      title: 'Modo de Configuración',
      type: 'string',
      group: 'general',
      description: 'Elige si deseas configurar el producto manualmente o que el sistema muestre productos en agotamiento de forma automática.',
      options: {
        list: [
          { title: '✍️ Manual (Configurado por el editor)', value: 'manual' },
          { title: '⚡ Automático (Detecta productos con bajo stock o destacados)', value: 'auto' },
        ],
        layout: 'radio',
      },
      initialValue: 'manual',
    }),
    defineField({
      name: 'delaySeconds',
      title: 'Tiempo de espera inicial (Segundos)',
      type: 'number',
      group: 'general',
      description: 'Segundos que espera antes de mostrarse en pantalla tras cargar la página.',
      initialValue: 6,
      validation: (Rule) => Rule.min(1).max(120),
    }),
    defineField({
      name: 'displayFrequency',
      title: 'Frecuencia de Visualización',
      type: 'string',
      group: 'general',
      description: 'Con qué frecuencia se le muestra al mismo usuario.',
      options: {
        list: [
          { title: 'Cada recarga / navegación (Siempre)', value: 'always' },
          { title: 'Una vez por sesión (Al cerrar, no vuelve a molestar en esa sesión)', value: 'session' },
          { title: 'Una vez cada 24 horas', value: 'daily' },
        ],
        layout: 'dropdown',
      },
      initialValue: 'session',
    }),
    defineField({
      name: 'position',
      title: 'Posición en Pantalla',
      type: 'string',
      group: 'general',
      options: {
        list: [
          { title: 'Abajo a la izquierda (Recomendado)', value: 'bottom-left' },
          { title: 'Abajo a la derecha', value: 'bottom-right' },
          { title: 'Abajo al centro', value: 'bottom-center' },
          { title: 'Arriba a la derecha', value: 'top-right' },
        ],
      },
      initialValue: 'bottom-left',
    }),

    // --- GRUPO MODO MANUAL ---
    defineField({
      name: 'product',
      title: 'Seleccionar Producto del Catálogo (Opcional)',
      type: 'reference',
      to: [{ type: 'product' }],
      group: 'manual',
      description: 'Si seleccionas un producto, se cargarán automáticamente su título, imagen, precio y enlace si no los personalizas abajo.',
      hidden: ({ parent }) => parent?.mode === 'auto',
    }),
    defineField({
      name: 'customTitle',
      title: 'Título de Urgencia',
      type: 'string',
      group: 'manual',
      description: 'Ej: ¡Agotándose Rápido! Tela Brush Sublimada',
      initialValue: '¡Agotándose Rápido! Tela Brush Sublimada',
      hidden: ({ parent }) => parent?.mode === 'auto',
    }),
    defineField({
      name: 'customMessage',
      title: 'Mensaje de Escasez / Urgencia',
      type: 'text',
      rows: 2,
      group: 'manual',
      description: 'Ej: Quedan solo 8 metros en inventario. ¡Más de 14 clientes lo tienen en su carrito!',
      initialValue: 'Quedan solo 8 metros disponibles. ¡Alta demanda en las últimas horas!',
      hidden: ({ parent }) => parent?.mode === 'auto',
    }),
    defineField({
      name: 'badgeText',
      title: 'Etiqueta / Badge Superior',
      type: 'string',
      group: 'manual',
      description: 'Ej: 🔥 ¡ÚLTIMAS UNIDADES!, ⚠️ QUEDAN POCOS METROS, ⚡ ALTA DEMANDA',
      initialValue: '🔥 ¡ÚLTIMAS UNIDADES!',
      hidden: ({ parent }) => parent?.mode === 'auto',
    }),
    defineField({
      name: 'stockRemaining',
      title: 'Cantidad restante a mostrar',
      type: 'number',
      group: 'manual',
      description: 'Número de metros o unidades que quedan.',
      initialValue: 6,
      hidden: ({ parent }) => parent?.mode === 'auto',
    }),
    defineField({
      name: 'stockUnit',
      title: 'Unidad de Stock',
      type: 'string',
      group: 'manual',
      description: 'Ej: metros, unidades, rollos',
      initialValue: 'metros',
      hidden: ({ parent }) => parent?.mode === 'auto',
    }),
    defineField({
      name: 'customImage',
      title: 'Imagen Personalizada',
      type: 'image',
      group: 'manual',
      options: { hotspot: true },
      description: 'Imagen del producto o icono de advertencia (opcional si ya seleccionaste un producto arriba).',
      hidden: ({ parent }) => parent?.mode === 'auto',
    }),
    defineField({
      name: 'buttonText',
      title: 'Texto del Botón CTA',
      type: 'string',
      group: 'manual',
      description: 'Ej: Ver Producto, ¡Comprar Antes que se Agote!, Aprovechar Ahora',
      initialValue: 'Ver Producto',
      hidden: ({ parent }) => parent?.mode === 'auto',
    }),
    defineField({
      name: 'buttonUrl',
      title: 'Enlace personalizado del Botón',
      type: 'string',
      group: 'manual',
      description: 'URL a la que redirige (opcional, por defecto irá al producto seleccionado o a /tienda).',
      hidden: ({ parent }) => parent?.mode === 'auto',
    }),
    defineField({
      name: 'socialProofCount',
      title: 'Personas viendo esto (Social Proof)',
      type: 'number',
      group: 'manual',
      description: 'Ej: 14 (Mostrará "14 personas viendo esto ahora")',
      initialValue: 12,
      hidden: ({ parent }) => parent?.mode === 'auto',
    }),

    // --- GRUPO MODO AUTOMÁTICO ---
    defineField({
      name: 'autoStockThreshold',
      title: 'Umbral de Stock Bajo',
      type: 'number',
      group: 'auto',
      description: 'Mostrará automáticamente productos que tengan un stock menor o igual a este número.',
      initialValue: 15,
      hidden: ({ parent }) => parent?.mode !== 'auto',
    }),
    defineField({
      name: 'autoBadgeText',
      title: 'Etiqueta por defecto en Automático',
      type: 'string',
      group: 'auto',
      description: 'Ej: 🔥 ¡CASI AGOTADO!',
      initialValue: '🔥 ¡CASI AGOTADO!',
      hidden: ({ parent }) => parent?.mode !== 'auto',
    }),
    defineField({
      name: 'autoMessageTemplate',
      title: 'Plantilla de Mensaje Automático',
      type: 'string',
      group: 'auto',
      description: 'Plantilla dinámica. Puedes usar {stock} para insertar los metros/unidades restantes.',
      initialValue: '¡Quedan solo {stock} disponibles! Producto en alta demanda hoy.',
      hidden: ({ parent }) => parent?.mode !== 'auto',
    }),

    // --- GRUPO DISEÑO Y APARIENCIA ---
    defineField({
      name: 'themeColor',
      title: 'Color / Tema Visual',
      type: 'string',
      group: 'appearance',
      options: {
        list: [
          { title: '🔥 Rojo Urgencia Intenso', value: 'red' },
          { title: '⚡ Ámbar / Naranja Alerta', value: 'amber' },
          { title: '🖤 Oscuro Elegante (Dark Luxury)', value: 'dark' },
          { title: '🔵 Azul Marca Telas Real', value: 'primary' },
        ],
        layout: 'radio',
      },
      initialValue: 'red',
    }),
    defineField({
      name: 'showProgressBar',
      title: 'Mostrar Barra de Progreso de Agotamiento',
      type: 'boolean',
      group: 'appearance',
      description: 'Muestra una barra visual indicando que el stock está cerca del 100% vendido.',
      initialValue: true,
    }),
    defineField({
      name: 'progressPercent',
      title: 'Porcentaje de Stock Vendido (%)',
      type: 'number',
      group: 'appearance',
      description: 'Porcentaje para la barra visual (Ej: 85 para mostrar 85% vendido).',
      initialValue: 85,
      validation: (Rule) => Rule.min(10).max(99),
      hidden: ({ parent }) => !parent?.showProgressBar,
    }),
    defineField({
      name: 'showSocialProof',
      title: 'Mostrar Contador de Personas Interesadas',
      type: 'boolean',
      group: 'appearance',
      description: 'Muestra el indicador de "X personas viendo esto ahora mismo".',
      initialValue: true,
    }),
  ],
  preview: {
    select: {
      isActive: 'isActive',
      mode: 'mode',
      customTitle: 'customTitle',
      badgeText: 'badgeText',
      productTitle: 'product.title',
      media: 'customImage',
      productMedia: 'product.images.0',
    },
    prepare({ isActive, mode, customTitle, badgeText, productTitle, media, productMedia }) {
      const isManual = mode !== 'auto'
      const titleText = isManual ? (customTitle || productTitle || 'Popup Manual') : '⚡ Popup Automático de Agotamiento'
      return {
        title: titleText,
        subtitle: `${isActive ? '🟢 Activo' : '🔴 Inactivo'} | ${isManual ? 'Manual' : 'Automático'} | ${badgeText || 'Urgencia'}`,
        media: media || productMedia || Flame,
      }
    },
  },
})
